### ISSUE TITLE
Not working anymore (two-factor authentication)

### ISSUE THREAD

**Issue by jbein** [muhlba91/icloud#12]
Hey,
At first I have to say that this tool is awesome! 

Sadly it is not working anymore for me. I think there are some issues with the new two-factor authentication from apple. Can you confirm this?

Cheers,
Jan

**Comment by muhlba91** [comment]
Hi!

Yes, unfortuantely, I can confirm that querying the Apple servers using 2FA is not working the same way.
I am aware of this problem since a while but decided to not invest too much time for it as disabling 2FA is done quickly as a hotfix and it only affects a very small number of people (that I got aware of), at the moment.

Best, Daniel :)

**Comment by basbodart** [comment]
Hi,

I experienced the problem too but I found a workaround.
You actually have to ENABLE 2FA on your icloud account then generate a new app-specific password that you'll have to use instead of your usual password. Still use your usual ID.

I got the idea after reading this : https://www.macrumors.com/2017/05/16/third-party-apps-passwords-icloud-access/

Hope this helps.

Cheers,
Bastien

**Comment by jbein** [comment]
Hello Bastien,

Works like a charm. Thank's a lot for the hint!

Cheers,
Jan

**Comment by marcelstoer** [comment]
Contrary to the issue label (Enhancement/Feature) I don't think this would have to result in code changes. Simply mentioning this in the documentation would be enough to keep this software useable for people with 2FA enabled. I don't understand why the issue is closed.

**Comment by muhlba91** [comment]
Hi,

thank you!
Yes, I am planning on updating the documentation for this to include a note on enabling an app-specific password.

**Comment by marcelstoer** [comment]
I actually wanted to provide a PR for this issue but #16 kind-of stopped me 😉
